// Code generated by MockGen. DO NOT EDIT.
// Source: reset_repository.go
//
// Generated by this command:
//
//	mockgen -source=reset_repository.go -destination=mock/reset_repository_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockResetTokenRepository is a mock of ResetTokenRepository interface.
type MockResetTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockResetTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockResetTokenRepositoryMockRecorder is the mock recorder for MockResetTokenRepository.
type MockResetTokenRepositoryMockRecorder struct {
	mock *MockResetTokenRepository
}

// NewMockResetTokenRepository creates a new mock instance.
func NewMockResetTokenRepository(ctrl *gomock.Controller) *MockResetTokenRepository {
	mock := &MockResetTokenRepository{ctrl: ctrl}
	mock.recorder = &MockResetTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResetTokenRepository) EXPECT() *MockResetTokenRepositoryMockRecorder {
	return m.recorder
}

// SaveToken mocks base method.
func (m *MockResetTokenRepository) SaveToken(ctx context.Context, token string, userID uuid.UUID, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveToken", ctx, token, userID, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveToken indicates an expected call of SaveToken.
func (mr *MockResetTokenRepositoryMockRecorder) SaveToken(ctx, token, userID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveToken", reflect.TypeOf((*MockResetTokenRepository)(nil).SaveToken), ctx, token, userID, ttl)
}

// UseToken mocks base method.
func (m *MockResetTokenRepository) UseToken(ctx context.Context, token string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UseToken", ctx, token)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UseToken indicates an expected call of UseToken.
func (mr *MockResetTokenRepositoryMockRecorder) UseToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UseToken", reflect.TypeOf((*MockResetTokenRepository)(nil).UseToken), ctx, token)
}
